### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by amivaleo**
Hi,
I translated your extension into my native language.
I hope you appreciate this.
Let me know if you want to fix some term. I already tested it on my PC.

;)

### CODE REVIEW

**Comment by Maestroschan** [comment]
Thank you, i will upload it on the official website tomorrow

**Comment by amivaleo** [comment]
I'm sorry, I don't know how to contact you in other ways.
I'm working on this: https://github.com/amivaleo/Emojis
Maybe you would like to take a look. :)

**Comment by Maestroschan** [comment]
It looks amazing, but i can't test it for now (i totally broke my Debian and Gnome refuses to work 😢)

**Comment by amivaleo** [comment]
It's a work in progress. The horizontal tabs still don't work.
I know nothing about java (i'm not even sure that this is java! o.o) so I'm learning from the other extensions.
We can both work on this, if you want. It would be an honor and a pleasure for me, and also an occasion to learn more about gnome extension. :)
It's up to you, no pressure from me. Every single hint would be appreciated. ;)

**Comment by Maestroschan** [comment]
It's javascript, but i learned it from other extensions too ;)
I will try it when my Gnome will be functional, for now i'm trying to adapt the extension to Cinnamon

**Pull request merged**
