### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by morealaz**
Add installation instruction for Arch users.

### CODE REVIEW

**Comment by morealaz** [comment]
Add screenshot with colored emoji from emojione

**Comment by Maestroschan** [comment]
Oh, you have colored emojis ?! It's amazing, i can't have it on my Debian, could you please redo the screenshot with:
- the setting window opened on the "appearance" tab,
- the extension opened with the smileys&people category like you did,
- the cursor **visible** over the corresponding button,
- no keyboard focus in the search entry so we can see the hint text ? (hover the category title to remove the focus from it)

It can replace my old screenshot of the former version, and i would also like to post it as the official screenshot on extensions.gnome.org

**Comment by morealaz** [comment]
@Maestroschan : I take a new screenshot.

**Comment by Maestroschan** [comment]
Thank you !

**Pull request merged**
